name: cuscus
version: 0.0.1
author: Mariana Marasoiu <mariana.marasoiu@gmail.com
description: A research interface for creating visualisations based on spreadsheets.
environment:
  sdk: ^2.0.0

dependencies:
  petitparser: any
  js: any
  possum:
    git: git://github.com/lukechurch/possum.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
